Draft: Add support for Cargo projects in Drafter and in action macros
serpent-os/boulder pull request #2
Opened 2022-08-15 09:30 UTC by livingsilver94

2022-08-27 19:44 UTC, GZGavinZhao commented
Add `%JOBS%`?

2022-08-27 19:59 UTC, livingsilver94 commented
Oh, right, nice suggestion! Many thanks!

2022-09-12 19:26 UTC, ermo requested changes
Looks nice.

I assume you have tested it locally to be working?

2022-09-12 19:26 UTC, ermo commented on source/drafter/build/rust.d
> + * Authors: Â© 2020-2022 Serpent OS Developers
That Â looks weird...?

2022-09-12 19:52 UTC, livingsilver94 commented
> I assume you have tested it locally to be working?

Still have to. Let me try to package rust into venom to perform a real life test, otherwise should I fail at it i'll perform a simple no-op test.

2023-02-21 09:38 UTC, closed without merging